[package]
name = "fmp4"
version = "0.1.0"
authors = ["Felix Kaaman <tmtu@tmtu.ee>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
byteorder = "1.3"
four-cc = "0.1"
bitflags = "1.0"
thiserror = "1.0"
bytes = "1.0"
