[package]
name = "wip"
version = "0.1.0"
authors = ["Felix Kaaman <tmtu@tmtu.ee>"]
edition = "2018"

[dependencies]
axum = { version = "0.2", features = ["ws"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
futures = "0.3"
futures-util = "0.3"
async-channel = "1.6"
async-trait = "0.1"

bytesize = "1.1"
e-ring = "0.3"
slog = "2.7"
slog-async = "2.7"
slog-term = "2.8"
thiserror = "1.0"
stop-token = { git = "https://github.com/soruh/stop-token" }
failure = "0.1"
anyhow = "1.0"
chrono = "0.4"
hex-slice = "0.1"
gcd = "2.0"
bytes = "1.0"
log = "0.4"
byteorder = "1.4"
base64 = "0.13"

webrtc = "0.2"
flvparse = "0.1"
rml_rtmp = "0.4"
rfc6381-codec = { git = "https://github.com/dholroyd/rfc6381-codec" }
h264-reader = { git = "https://github.com/dholroyd/h264-reader" }
fmp4 = { path = "fmp4" }
tracing-subscriber = "*"

dotenv = "0.15.0"

