[workspace]
members = [
    "sh-media",
    "sh-fmp4",
    "sh-ingest-rtmp",
    "sh-transport-mse",
    "streamhead",
]

[patch.crates-io]
av-codec = { git = "https://github.com/rust-av/rust-av" }
av-data = { git = "https://github.com/rust-av/rust-av" }
av-format = { git = "https://github.com/rust-av/rust-av" }
av-bitstream = { git = "https://github.com/rust-av/rust-av" }