[package]
name = "wip"
version = "0.1.0"
authors = ["Felix Kaaman <tmtu@tmtu.ee>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
futures-util = "0.3"
async-channel = "1.6"
async-trait = "0.1"

bytesize = "1.1"
e-ring = "0.3"
slog = "2.7"
slog-async = "2.7"
slog-term = "2.8"
thiserror = "1.0"
stop-token = { git = "https://github.com/soruh/stop-token" }
failure = "0.1"
anyhow = "1.0"
chrono = "0.4"
hex-slice = "0.1"
gcd = "2.0"
bytes = "1.0"
log = "0.4"
byteorder = "1.4"
base64 = "0.13"

flvparse = "0.1"
rml_rtmp = "0.4"
rfc6381-codec = { git = "https://github.com/dholroyd/rfc6381-codec" }
# mpeg2ts-reader = "*"
h264-reader = { git = "https://github.com/dholroyd/h264-reader" }
fmp4 = { path = "fmp4" }

actix-web-actors = "4.0.0-beta.7"
actix-web = "4.0.0-beta.9"
actix-files = "0.6.0-beta.7"
actix = "0.12"
actix-rt = "2.3"
dotenv = "0.15.0"

