name: Rust

on:
  push:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Deploy to dev
      env:
        DEPLOY_KEY: ${{ secrets.RELKOJ_KEY }}
      run: curl --basic -u "$DEPLOY_KEY" -F "bin=@target/release/wip" https://dev.streamhead.mavulp.com/deploy
