name: Deploy to dev

on:
  push:
    branches: [ trunk, deploy-test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend
      run: bash ./build/package-rpm.sh
    - name: Build ingest
      run: bash ./build/package-ingest-rpm.sh

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
        ARGS: >-
          -rltgoDzvO
          --exclude='.git'
          --exclude='node_modules/'
        REMOTE_HOST: ${{ secrets.REMOTE_HOST_DEV }}
        REMOTE_USER: ${{ secrets.REMOTE_USER_DEV }}
        TARGET: /home/deployer

    - name: Post Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST_DEV }}
        username: ${{ secrets.REMOTE_USER_DEV }}
        key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
        port: 22
        script: |
          /home/${{ secrets.REMOTE_USER_DEV }}/deploy.sh
