name: Rust

on:
  push:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Deploy to dev
      env:
        DEPLOY_KEY: ${{ secrets.RELKOJ_KEY }}
      run: 'curl --silent --show-error --fail --basic -u "$DEPLOY_KEY" -H "git-commit: $GITHUB_SHA" -F "bin=@target/release/streamhead" https://dev.streamhead.mavulp.com/deploy'
