name: Deploy qwer (dev)

on: workflow_dispatch
#  push:
#    branches: [ trunk, deploy-test, deploy-test-2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: fkaa/qwer/.github/workflows/build.yml@v1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@master
      with:
        name: qwer-rpm
        path: ./artifacts/

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
        ARGS: >-
          -rtzv
        REMOTE_HOST: ${{ secrets.REMOTE_HOST_DEV }}
        REMOTE_USER: ${{ secrets.REMOTE_USER_DEV }}
        SOURCE: "artifacts/RPMS/x86_64/"
        TARGET: /home/${{ secrets.REMOTE_USER_DEV }}/rpms

    - name: Post Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST_DEV }}
        username: ${{ secrets.REMOTE_USER_DEV }}
        key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
        port: 22
        script: |
          sudo /home/${{ secrets.REMOTE_USER_DEV }}/deploy.sh
